### ISSUE TITLE
Register for National Zoning Atlas Slack workspace.

### ISSUE THREAD

**Issue by thebestyoshibird** [thebestyoshibird/VT_Zoning_Atlas#26]

**Comment by zoesreden** [comment]
@thebestyoshibird Can you add the link for people to sign up for the space?

**Comment by thebestyoshibird** [comment]
They have recently changed their protocols, so now I need everyone's best email address. Then I (or you, if you want!) send a request for administrator approval to join. They won't let us send out links to register anymore, I guess. That's new to me!
