### ISSUE TITLE
Register for Vermont Zoning Atlas Slack workspace.

### ISSUE THREAD

**Issue by thebestyoshibird** [thebestyoshibird/VT_Zoning_Atlas#27]

**Comment by zoesreden** [comment]
You've all been invited, comment when you've accepted the invite.

**Comment by tuckers15** [comment]
I've joined the VT Zoning Atlas Slack

**Comment by eeash** [comment]
I've accepted the invite

**Comment by pschorra** [comment]
I've accepted the invite and commented in the Slack.
________________________________

**Comment by thebestyoshibird** [comment]
Sorry, everyone - this task used to have the link embedded in it, but I can see that that has vanished. https://edit.zoningatlas.org/signup

**Comment by ZWinigrad** [comment]
I have joined the Vermont Zoning Atlas slack

**Comment by zoesreden** [comment]
Everyone has signed up for the slack.
