### ISSUE TITLE
Review the How-To Guide

### ISSUE THREAD

**Issue by thebestyoshibird** [thebestyoshibird/VT_Zoning_Atlas#3]
Review the section of guide How to Build a Zoning Atlas that is relevant to your assignment. Check out the training packet, too, for supplemental information.

Guide attached below.

[How to Make a Zoning Atlas Version 2.pdf](https://github.com/thebestyoshibird/VT_Zoning_Atlas/files/13601927/How.to.Make.a.Zoning.Atlas.Version.2.pdf)

[TrainingPacket_Fall2023.pdf](https://github.com/thebestyoshibird/VT_Zoning_Atlas/files/13601933/TrainingPacket_Fall2023.pdf)

**Comment by zoesreden** [comment]
Please add a comment when you're done.

**Comment by eeash** [comment]
Done

**Comment by ZWinigrad** [comment]
Done

**Comment by pschorra** [comment]
Finished

**Comment by tuckers15** [comment]
Done

**Comment by zoesreden** [comment]
Everyone should have it.
