### ISSUE TITLE
Enter district information for Pittsford.

### ISSUE THREAD

**Issue by zoesreden** [thebestyoshibird/VT_Zoning_Atlas#45]
Enter dimensional standards, due process requirements, and all other district information for each zoning district.

**Comment by thebestyoshibird** [comment]
Hey, everyone! Are you working on Pittsfield or Pittsford? They are two separate towns in Rutland County.

**Comment by thebestyoshibird** [comment]
Changed the task title to reflect that you are working on district information for Pittsford, not Pittsfield.
