### ISSUE TITLE
Register for Editor tool access

### ISSUE THREAD

**Issue by thebestyoshibird** [thebestyoshibird/VT_Zoning_Atlas#6]
Link to register: https://edit.zoningatlas.org/signup

Training video on getting started in Editor: https://youtu.be/g-4cy0wRah4?feature=shared

**Comment by thebestyoshibird** [comment]
@zoesreden This is probably the fastest step everyone can take. It's low-hanging fruit but incredibly important! Once you've registered for the Editor tool, please email me or Zoe and let us know which email address you used to join so we can assign you to the Vermont team inside the content management system.

**Comment by zoesreden** [comment]
@thebestyoshibird Sounds good!

**Comment by thebestyoshibird** [comment]
@tuckers15 Let me know when you get the invite to join and you register! Then I can add you to the team and this task, too, can be marked as complete!

**Comment by tuckers15** [comment]
@thebestyoshibird I have registered and am on the team.

**Comment by zoesreden** [comment]
Everyone is signed up.
