### ISSUE TITLE
Notify Yoshi to add you to team in Editor

### ISSUE THREAD

**Issue by thebestyoshibird** [thebestyoshibird/VT_Zoning_Atlas#7]
Send a note to Yoshi in Slack and let her know the email address you used to register so she can find you among the newly-registered Editor users who aren't yet assigned a team. Your exact email address is important - she can't find you if she uses the wrong address!

**Comment by zoesreden** [comment]
Add a comment once you've sent a message to Yoshi in Slack with the email you used to sign up for the zoning atlas editor.

**Comment by ZWinigrad** [comment]
I have sent a message in slack

**Comment by eeash** [comment]
I sent a message

**Comment by thebestyoshibird** [comment]
@tuckers15 I sent an invite for you to join Editor at the email address you sent me in Slack!

@eeash @ZWinigrad @pschorra You are all set! Once @tuckers15 is added to the team, I can mark this task as Done.

**Comment by tuckers15** [comment]
@thebestyoshibird I've joined the editor.

**Comment by zoesreden** [comment]
Everyone has joined editor.
