### ISSUE TITLE
Review the workflow for geospatial file cleanup

### ISSUE THREAD

**Issue by thebestyoshibird** [thebestyoshibird/VT_Zoning_Atlas#9]
Workflow attached below.

[WorkflowD1&2_v5.drawio (1).pdf](https://github.com/thebestyoshibird/VT_Zoning_Atlas/files/13601915/WorkflowD1.2_v5.drawio.1.pdf)

**Comment by zoesreden** [comment]
Please comment once you have reviewed the process.

**Comment by eeash** [comment]
Done

**Comment by pschorra** [comment]
Finished

**Comment by ZWinigrad** [comment]
Done
